### ISSUE TITLE
请问为什么官网上提供的微调脚本最后加了--deepspeed参数，但是finetune_hf.py里面识别不了这个参数？

### ISSUE THREAD

**Issue by Strivin0311** [We-IOT/chatglm3_6b_finetune#3]

**Comment by We-IOT** [comment]
deepspeed是微软的多卡分布式框架，我们现在的finetune_hf.py是在单卡下运行的

**Comment by Strivin0311** [comment]
> deepspeed是微软的多卡分布式框架，我们现在的finetune_hf.py是在单卡下运行的

我知道ds是啥哈哈，我就是不清楚为啥脚本和代码对不上，没事啦，我看到config里也可以设置，谢谢！
