### ISSUE TITLE
合并模型的时候为什么会出现can't set attribute 'eos_token'

### ISSUE THREAD

**Issue by 1523826455647** [We-IOT/chatglm3_6b_finetune#4]
合并模型的时候为什么会出现can't set attribute 'eos_token'

**Comment by We-IOT** [comment]
https://github.com/We-IOT/chatglm3_6b_finetune/issues/1

**Comment by feifei05** [comment]
transformers==4.38.2版本太高了，我用的transformers==4.34.0的环境去合并模型，没问题
